# ${config.serverName}

${config.description}

## Generated by MCP Server Builder

This MCP server was automatically generated and provides the following capabilities:

## Tools

<#list config.tools as tool>
### ${tool.name}

${tool.description}

**Parameters:**
<#list tool.parameters as param>
- `${param.name}` (${param.type})<#if param.required> **required**</#if>: ${param.description}
</#list>

</#list>
<#if config.resources?? && config.resources?size gt 0>
## Resources

<#list config.resources as resource>
### ${resource.name}

- **URI:** `${resource.uri}`
- **MIME Type:** `${resource.mimeType}`
- **Description:** ${resource.description}

</#list>
</#if>

## Installation

1. Install dependencies:
```bash
npm install
```

2. Build the server:
```bash
npm run build
```

## Usage with Claude Desktop

Add this to your Claude Desktop configuration file:

**MacOS:** `~/Library/Application Support/Claude/claude_desktop_config.json`
**Windows:** `%APPDATA%\Claude\claude_desktop_config.json`

```json
{
  "mcpServers": {
    "${config.serverName}": {
      "command": "node",
      "args": ["/absolute/path/to/this/server/build/index.js"]
    }
  }
}
```

## Development

Watch mode for development:
```bash
npm run watch
```

## License

MIT
